---
- name: install and start Apache HTTPD
  hosts: web
  tasks:
   - name: httpd package is present
     apt:
      name:
        - apache2
        - firewalld
      state: latest


   - name: correct index.html is present
     copy: 
      src: files/index.html
      dest: /var/www/html/index.html

   - name: Enable service apache 2
     service: 
      name: apache2
      state: started
      enabled: true 

   - name: Enable firewalld and running
     service:
       name: firewalld
       state: started
       enabled: true

   - name: Firewalld permits http service
     firewalld:
       port: 80/tcp
       permanent: true
       state: enabled
       immediate: yes


   - name: Verify if exist the line FUNCIONOU!!!! COPIOU!!!!
     lineinfile:
       path: /var/www/html/index.html
       line: 'FUNCIONOU!!!! COPIOU!!!!'
       state: present  
   
- name: Install mysqldb
  hosts: db
  # remote_user: usuarioDoHostDB
  # become: yes
  tasks:
    - name: Install mysql
      apt:
        name: mysql-server
        state: latest

    - name: Enable Service mysql
      service: 
        name: mysql
        enabled: true

