---
- name: install and start Apache HTTPD
  hosts: web
  tasks:
   - name: httpd package is present
     apt:
      name: apache2
      update_cache: yes
      state: present


   - name: correct index.html is present
     copy: 
      src: files/index.html
      dest: /var/www/html/index.html

   - name: httpd is started
     service: 
      name: apache2
      state: started
      enabled: true 
